[theme]

# option 1
primaryColor="#5b04b9"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"

# # option 2
# primaryColor="#5b04b9"
# backgroundColor="#808495"
# secondaryBackgroundColor= "#140125"
# textColor="#f0f0f5"
